
<?php

class Bdd
{
    private $host;
    private $username;
    private $password;
    private $port;
    private $className;

    public function __construct()
    {

        $this->host = 'smtp.mailtrap.io';
        $this->username = '884afdc00ba043';
        $this->password = 'a22bcdae3bac95';
        $this->port = '2525';
        $this->className = 'Smtp';
    }


}


?>

<?php

use PHPMailer\PHPMailer\PHPMailer;
require 'path/to/composer/vendor/autoload.php';
$mail->isSMTP();
$mail->Host = 'smtp.mailtrap.io';
$mail->SMTPAuth = true;
$mail->Username = 'paste one generated by Mailtrap';
$mail->Password = 'paste one generated by Mailtrap’;

$mail->SMTPSecure = 'tls';

$mail->Port = 2525;

$mail->setFrom('from@example.com', 'First Last');
$mail->addReplyTo('towho@example.com', 'John Doe';

$mail->isHTML(true);

$mail->Subject = "PHPMailer SMTP test";
$mail->addEmbeddedImage('path/to/image_file.jpg', 'image_cid');
$mail->Body = '<img src="cid:image_cid"> Mail body in HTML';
$mail->AltBody = 'This is the plain text version of the email content';

if(!$mail->send()){
    echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
}else{
    echo 'Message has been sent';